//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hurricane.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HurricaneEntities : DbContext
    {
        public HurricaneEntities()
            : base("name=HurricaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<local_tracks> local_tracks { get; set; }
        public DbSet<playlist_items> playlist_items { get; set; }
        public DbSet<playlist> playlists { get; set; }
        public DbSet<track> tracks { get; set; }
    }
}
