//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hurricane.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class local_tracks
    {
        public int TrackId { get; set; }
        public string Path { get; set; }
        public string Extension { get; set; }
    }
}
