//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hurricane.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Album { get; set; }
        public int TrackNumber { get; set; }
        public short Year { get; set; }
        public int kHz { get; set; }
        public int kbps { get; set; }
        public long AuthenticationCode { get; set; }
        public System.DateTime TimeAdded { get; set; }
        public System.DateTime LastTimePlayed { get; set; }
        public sbyte TrackType { get; set; }
    }
}
